/*
 * This file is generated by jOOQ.
 */
package model.tables.pojos;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "PASAJERO", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_7", columnNames = {"ID"})
})
public class Pasajero implements Serializable {

    private static final long serialVersionUID = -1583503249;

    private Integer id;
    private String  nombres;
    private String  edad;
    private String  genero;

    public Pasajero() {}

    public Pasajero(Pasajero value) {
        this.id = value.id;
        this.nombres = value.nombres;
        this.edad = value.edad;
        this.genero = value.genero;
    }

    public Pasajero(
        Integer id,
        String  nombres,
        String  edad,
        String  genero
    ) {
        this.id = id;
        this.nombres = nombres;
        this.edad = edad;
        this.genero = genero;
    }

    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public Pasajero setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "NOMBRES", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNombres() {
        return this.nombres;
    }

    public Pasajero setNombres(String nombres) {
        this.nombres = nombres;
        return this;
    }

    @Column(name = "EDAD", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getEdad() {
        return this.edad;
    }

    public Pasajero setEdad(String edad) {
        this.edad = edad;
        return this;
    }

    @Column(name = "GENERO", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    public String getGenero() {
        return this.genero;
    }

    public Pasajero setGenero(String genero) {
        this.genero = genero;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pasajero (");

        sb.append(id);
        sb.append(", ").append(nombres);
        sb.append(", ").append(edad);
        sb.append(", ").append(genero);

        sb.append(")");
        return sb.toString();
    }
}
