/*
 * This file is generated by jOOQ.
 */
package model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "RUTA", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_2", columnNames = {"ID"})
})
public class Ruta implements Serializable {

    private static final long serialVersionUID = 1709804648;

    private Integer   id;
    private String    nombre;
    private String    numero;
    private LocalDate inicio;
    private LocalDate fin;

    public Ruta() {}

    public Ruta(Ruta value) {
        this.id = value.id;
        this.nombre = value.nombre;
        this.numero = value.numero;
        this.inicio = value.inicio;
        this.fin = value.fin;
    }

    public Ruta(
        Integer   id,
        String    nombre,
        String    numero,
        LocalDate inicio,
        LocalDate fin
    ) {
        this.id = id;
        this.nombre = nombre;
        this.numero = numero;
        this.inicio = inicio;
        this.fin = fin;
    }

    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public Ruta setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "NOMBRE", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNombre() {
        return this.nombre;
    }

    public Ruta setNombre(String nombre) {
        this.nombre = nombre;
        return this;
    }

    @Column(name = "NUMERO", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNumero() {
        return this.numero;
    }

    public Ruta setNumero(String numero) {
        this.numero = numero;
        return this;
    }

    @Column(name = "INICIO", nullable = false, precision = 10)
    @NotNull
    public LocalDate getInicio() {
        return this.inicio;
    }

    public Ruta setInicio(LocalDate inicio) {
        this.inicio = inicio;
        return this;
    }

    @Column(name = "FIN", nullable = false, precision = 10)
    @NotNull
    public LocalDate getFin() {
        return this.fin;
    }

    public Ruta setFin(LocalDate fin) {
        this.fin = fin;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ruta (");

        sb.append(id);
        sb.append(", ").append(nombre);
        sb.append(", ").append(numero);
        sb.append(", ").append(inicio);
        sb.append(", ").append(fin);

        sb.append(")");
        return sb.toString();
    }
}
