/*
 * This file is generated by jOOQ.
 */
package model.tables.pojos;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "TARJETA", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_CF", columnNames = {"ID"})
})
public class Tarjeta implements Serializable {

    private static final long serialVersionUID = -1812431241;

    private Integer id;
    private String  personalizado;
    private Long    saldo;
    private Integer pasajeroId;
    private Integer convenioId;

    public Tarjeta() {}

    public Tarjeta(Tarjeta value) {
        this.id = value.id;
        this.personalizado = value.personalizado;
        this.saldo = value.saldo;
        this.pasajeroId = value.pasajeroId;
        this.convenioId = value.convenioId;
    }

    public Tarjeta(
        Integer id,
        String  personalizado,
        Long    saldo,
        Integer pasajeroId,
        Integer convenioId
    ) {
        this.id = id;
        this.personalizado = personalizado;
        this.saldo = saldo;
        this.pasajeroId = pasajeroId;
        this.convenioId = convenioId;
    }

    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public Tarjeta setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "PERSONALIZADO", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    public String getPersonalizado() {
        return this.personalizado;
    }

    public Tarjeta setPersonalizado(String personalizado) {
        this.personalizado = personalizado;
        return this;
    }

    @Column(name = "SALDO", nullable = false, precision = 10)
    @NotNull
    public Long getSaldo() {
        return this.saldo;
    }

    public Tarjeta setSaldo(Long saldo) {
        this.saldo = saldo;
        return this;
    }

    @Column(name = "PASAJERO_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getPasajeroId() {
        return this.pasajeroId;
    }

    public Tarjeta setPasajeroId(Integer pasajeroId) {
        this.pasajeroId = pasajeroId;
        return this;
    }

    @Column(name = "CONVENIO_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getConvenioId() {
        return this.convenioId;
    }

    public Tarjeta setConvenioId(Integer convenioId) {
        this.convenioId = convenioId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tarjeta (");

        sb.append(id);
        sb.append(", ").append(personalizado);
        sb.append(", ").append(saldo);
        sb.append(", ").append(pasajeroId);
        sb.append(", ").append(convenioId);

        sb.append(")");
        return sb.toString();
    }
}
