/*
 * This file is generated by jOOQ.
 */
package model.tables.pojos;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "VEHICULO", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_A", columnNames = {"ID"})
})
public class Vehiculo implements Serializable {

    private static final long serialVersionUID = -1663859377;

    private Integer id;
    private String  palca;
    private Integer capacidad;
    private String  color;

    public Vehiculo() {}

    public Vehiculo(Vehiculo value) {
        this.id = value.id;
        this.palca = value.palca;
        this.capacidad = value.capacidad;
        this.color = value.color;
    }

    public Vehiculo(
        Integer id,
        String  palca,
        Integer capacidad,
        String  color
    ) {
        this.id = id;
        this.palca = palca;
        this.capacidad = capacidad;
        this.color = color;
    }

    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public Vehiculo setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "PALCA", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getPalca() {
        return this.palca;
    }

    public Vehiculo setPalca(String palca) {
        this.palca = palca;
        return this;
    }

    @Column(name = "CAPACIDAD", nullable = false, precision = 10)
    @NotNull
    public Integer getCapacidad() {
        return this.capacidad;
    }

    public Vehiculo setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
        return this;
    }

    @Column(name = "COLOR", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getColor() {
        return this.color;
    }

    public Vehiculo setColor(String color) {
        this.color = color;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vehiculo (");

        sb.append(id);
        sb.append(", ").append(palca);
        sb.append(", ").append(capacidad);
        sb.append(", ").append(color);

        sb.append(")");
        return sb.toString();
    }
}
