/*
 * This file is generated by jOOQ.
 */
package model.tables.pojos;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "VIAJE", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_4", columnNames = {"ID", "DISTANCIA"})
})
public class Viaje implements Serializable {

    private static final long serialVersionUID = -851863867;

    private Integer id;
    private Long    distancia;
    private Integer tarjetaId;
    private Integer vehiculoId;

    public Viaje() {}

    public Viaje(Viaje value) {
        this.id = value.id;
        this.distancia = value.distancia;
        this.tarjetaId = value.tarjetaId;
        this.vehiculoId = value.vehiculoId;
    }

    public Viaje(
        Integer id,
        Long    distancia,
        Integer tarjetaId,
        Integer vehiculoId
    ) {
        this.id = id;
        this.distancia = distancia;
        this.tarjetaId = tarjetaId;
        this.vehiculoId = vehiculoId;
    }

    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public Viaje setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "DISTANCIA", nullable = false, precision = 10)
    @NotNull
    public Long getDistancia() {
        return this.distancia;
    }

    public Viaje setDistancia(Long distancia) {
        this.distancia = distancia;
        return this;
    }

    @Column(name = "TARJETA_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getTarjetaId() {
        return this.tarjetaId;
    }

    public Viaje setTarjetaId(Integer tarjetaId) {
        this.tarjetaId = tarjetaId;
        return this;
    }

    @Column(name = "VEHICULO_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getVehiculoId() {
        return this.vehiculoId;
    }

    public Viaje setVehiculoId(Integer vehiculoId) {
        this.vehiculoId = vehiculoId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Viaje (");

        sb.append(id);
        sb.append(", ").append(distancia);
        sb.append(", ").append(tarjetaId);
        sb.append(", ").append(vehiculoId);

        sb.append(")");
        return sb.toString();
    }
}
