/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.List;

import model.Keys;
import model.Transmi;
import model.tables.records.TarjetaRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tarjeta extends TableImpl<TarjetaRecord> {

    private static final long serialVersionUID = 199308257;

    /**
     * The reference instance of <code>TRANSMI.TARJETA</code>
     */
    public static final Tarjeta TARJETA = new Tarjeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TarjetaRecord> getRecordType() {
        return TarjetaRecord.class;
    }

    /**
     * The column <code>TRANSMI.TARJETA.ID</code>.
     */
    public final TableField<TarjetaRecord, Integer> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>TRANSMI.TARJETA.PERSONALIZADO</code>.
     */
    public final TableField<TarjetaRecord, String> PERSONALIZADO = createField(DSL.name("PERSONALIZADO"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>TRANSMI.TARJETA.SALDO</code>.
     */
    public final TableField<TarjetaRecord, Long> SALDO = createField(DSL.name("SALDO"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>TRANSMI.TARJETA.PASAJERO_ID</code>.
     */
    public final TableField<TarjetaRecord, Integer> PASAJERO_ID = createField(DSL.name("PASAJERO_ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>TRANSMI.TARJETA.CONVENIO_ID</code>.
     */
    public final TableField<TarjetaRecord, Integer> CONVENIO_ID = createField(DSL.name("CONVENIO_ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>TRANSMI.TARJETA</code> table reference
     */
    public Tarjeta() {
        this(DSL.name("TARJETA"), null);
    }

    /**
     * Create an aliased <code>TRANSMI.TARJETA</code> table reference
     */
    public Tarjeta(String alias) {
        this(DSL.name(alias), TARJETA);
    }

    /**
     * Create an aliased <code>TRANSMI.TARJETA</code> table reference
     */
    public Tarjeta(Name alias) {
        this(alias, TARJETA);
    }

    private Tarjeta(Name alias, Table<TarjetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tarjeta(Name alias, Table<TarjetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Tarjeta(Table<O> child, ForeignKey<O, TarjetaRecord> key) {
        super(child, key, TARJETA);
    }

    @Override
    public Schema getSchema() {
        return Transmi.TRANSMI;
    }

    @Override
    public UniqueKey<TarjetaRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_CF;
    }

    @Override
    public List<UniqueKey<TarjetaRecord>> getKeys() {
        return Arrays.<UniqueKey<TarjetaRecord>>asList(Keys.CONSTRAINT_CF);
    }

    @Override
    public List<ForeignKey<TarjetaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TarjetaRecord, ?>>asList(Keys.FK_TARJETA_PASAJERO, Keys.FK_TARJETA_CONVENIO1);
    }

    public Pasajero pasajero() {
        return new Pasajero(this, Keys.FK_TARJETA_PASAJERO);
    }

    public Convenio convenio() {
        return new Convenio(this, Keys.FK_TARJETA_CONVENIO1);
    }

    @Override
    public Tarjeta as(String alias) {
        return new Tarjeta(DSL.name(alias), this);
    }

    @Override
    public Tarjeta as(Name alias) {
        return new Tarjeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tarjeta rename(String name) {
        return new Tarjeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tarjeta rename(Name name) {
        return new Tarjeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Long, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
