micronaut:
  application:
    name: orm
  datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: rodack
        password: rodack
        driverClassName: org.h2.Driver
