micronaut:
  application:
    name: orm
  datasources:
    default:
      url: jdbc:h2:tcp://127.0.1.1:9092/rodack;schema=transmi
      username: rodack
      password: rodack
      driverClassName: org.h2.Driver
      sql-dialect: 'H2'
