/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Convenio;
import model.tables.Estacion;
import model.tables.Pasajero;
import model.tables.Ruta;
import model.tables.Tarjeta;
import model.tables.Vehiculo;
import model.tables.Viaje;
import model.tables.records.ConvenioRecord;
import model.tables.records.EstacionRecord;
import model.tables.records.PasajeroRecord;
import model.tables.records.RutaRecord;
import model.tables.records.TarjetaRecord;
import model.tables.records.VehiculoRecord;
import model.tables.records.ViajeRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>TRANSMI</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConvenioRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
    public static final UniqueKey<EstacionRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
    public static final UniqueKey<PasajeroRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<RutaRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<TarjetaRecord> CONSTRAINT_CF = UniqueKeys0.CONSTRAINT_CF;
    public static final UniqueKey<VehiculoRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<ViajeRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EstacionRecord, RutaRecord> FK_ESTACION_RUTA1 = ForeignKeys0.FK_ESTACION_RUTA1;
    public static final ForeignKey<TarjetaRecord, PasajeroRecord> FK_TARJETA_PASAJERO = ForeignKeys0.FK_TARJETA_PASAJERO;
    public static final ForeignKey<TarjetaRecord, ConvenioRecord> FK_TARJETA_CONVENIO1 = ForeignKeys0.FK_TARJETA_CONVENIO1;
    public static final ForeignKey<ViajeRecord, TarjetaRecord> FK_VIAJE_TARJETA1 = ForeignKeys0.FK_VIAJE_TARJETA1;
    public static final ForeignKey<ViajeRecord, VehiculoRecord> FK_VIAJE_VEHICULO1 = ForeignKeys0.FK_VIAJE_VEHICULO1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ConvenioRecord> CONSTRAINT_C = Internal.createUniqueKey(Convenio.CONVENIO, "CONSTRAINT_C", new TableField[] { Convenio.CONVENIO.ID }, true);
        public static final UniqueKey<EstacionRecord> CONSTRAINT_B = Internal.createUniqueKey(Estacion.ESTACION, "CONSTRAINT_B", new TableField[] { Estacion.ESTACION.ID }, true);
        public static final UniqueKey<PasajeroRecord> CONSTRAINT_7 = Internal.createUniqueKey(Pasajero.PASAJERO, "CONSTRAINT_7", new TableField[] { Pasajero.PASAJERO.ID }, true);
        public static final UniqueKey<RutaRecord> CONSTRAINT_2 = Internal.createUniqueKey(Ruta.RUTA, "CONSTRAINT_2", new TableField[] { Ruta.RUTA.ID }, true);
        public static final UniqueKey<TarjetaRecord> CONSTRAINT_CF = Internal.createUniqueKey(Tarjeta.TARJETA, "CONSTRAINT_CF", new TableField[] { Tarjeta.TARJETA.ID }, true);
        public static final UniqueKey<VehiculoRecord> CONSTRAINT_A = Internal.createUniqueKey(Vehiculo.VEHICULO, "CONSTRAINT_A", new TableField[] { Vehiculo.VEHICULO.ID }, true);
        public static final UniqueKey<ViajeRecord> CONSTRAINT_4 = Internal.createUniqueKey(Viaje.VIAJE, "CONSTRAINT_4", new TableField[] { Viaje.VIAJE.ID, Viaje.VIAJE.DISTANCIA }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<EstacionRecord, RutaRecord> FK_ESTACION_RUTA1 = Internal.createForeignKey(Keys.CONSTRAINT_2, Estacion.ESTACION, "FK_ESTACION_RUTA1", new TableField[] { Estacion.ESTACION.RUTA_ID }, true);
        public static final ForeignKey<TarjetaRecord, PasajeroRecord> FK_TARJETA_PASAJERO = Internal.createForeignKey(Keys.CONSTRAINT_7, Tarjeta.TARJETA, "FK_TARJETA_PASAJERO", new TableField[] { Tarjeta.TARJETA.PASAJERO_ID }, true);
        public static final ForeignKey<TarjetaRecord, ConvenioRecord> FK_TARJETA_CONVENIO1 = Internal.createForeignKey(Keys.CONSTRAINT_C, Tarjeta.TARJETA, "FK_TARJETA_CONVENIO1", new TableField[] { Tarjeta.TARJETA.CONVENIO_ID }, true);
        public static final ForeignKey<ViajeRecord, TarjetaRecord> FK_VIAJE_TARJETA1 = Internal.createForeignKey(Keys.CONSTRAINT_CF, Viaje.VIAJE, "FK_VIAJE_TARJETA1", new TableField[] { Viaje.VIAJE.TARJETA_ID }, true);
        public static final ForeignKey<ViajeRecord, VehiculoRecord> FK_VIAJE_VEHICULO1 = Internal.createForeignKey(Keys.CONSTRAINT_A, Viaje.VIAJE, "FK_VIAJE_VEHICULO1", new TableField[] { Viaje.VIAJE.VEHICULO_ID }, true);
    }
}
