/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Convenio;
import model.tables.Estacion;
import model.tables.Pasajero;
import model.tables.Ruta;
import model.tables.Tarjeta;
import model.tables.Vehiculo;
import model.tables.Viaje;


/**
 * Convenience access to all tables in TRANSMI
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>TRANSMI.CONVENIO</code>.
     */
    public static final Convenio CONVENIO = Convenio.CONVENIO;

    /**
     * The table <code>TRANSMI.ESTACION</code>.
     */
    public static final Estacion ESTACION = Estacion.ESTACION;

    /**
     * The table <code>TRANSMI.PASAJERO</code>.
     */
    public static final Pasajero PASAJERO = Pasajero.PASAJERO;

    /**
     * The table <code>TRANSMI.RUTA</code>.
     */
    public static final Ruta RUTA = Ruta.RUTA;

    /**
     * The table <code>TRANSMI.TARJETA</code>.
     */
    public static final Tarjeta TARJETA = Tarjeta.TARJETA;

    /**
     * The table <code>TRANSMI.VEHICULO</code>.
     */
    public static final Vehiculo VEHICULO = Vehiculo.VEHICULO;

    /**
     * The table <code>TRANSMI.VIAJE</code>.
     */
    public static final Viaje VIAJE = Viaje.VIAJE;
}
