/*
 * This file is generated by jOOQ.
 */
package model;


import java.util.Arrays;
import java.util.List;

import model.tables.Convenio;
import model.tables.Estacion;
import model.tables.Pasajero;
import model.tables.Ruta;
import model.tables.Tarjeta;
import model.tables.Vehiculo;
import model.tables.Viaje;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transmi extends SchemaImpl {

    private static final long serialVersionUID = 1687696522;

    /**
     * The reference instance of <code>TRANSMI</code>
     */
    public static final Transmi TRANSMI = new Transmi();

    /**
     * The table <code>TRANSMI.CONVENIO</code>.
     */
    public final Convenio CONVENIO = Convenio.CONVENIO;

    /**
     * The table <code>TRANSMI.ESTACION</code>.
     */
    public final Estacion ESTACION = Estacion.ESTACION;

    /**
     * The table <code>TRANSMI.PASAJERO</code>.
     */
    public final Pasajero PASAJERO = Pasajero.PASAJERO;

    /**
     * The table <code>TRANSMI.RUTA</code>.
     */
    public final Ruta RUTA = Ruta.RUTA;

    /**
     * The table <code>TRANSMI.TARJETA</code>.
     */
    public final Tarjeta TARJETA = Tarjeta.TARJETA;

    /**
     * The table <code>TRANSMI.VEHICULO</code>.
     */
    public final Vehiculo VEHICULO = Vehiculo.VEHICULO;

    /**
     * The table <code>TRANSMI.VIAJE</code>.
     */
    public final Viaje VIAJE = Viaje.VIAJE;

    /**
     * No further instances allowed
     */
    private Transmi() {
        super("TRANSMI", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Convenio.CONVENIO,
            Estacion.ESTACION,
            Pasajero.PASAJERO,
            Ruta.RUTA,
            Tarjeta.TARJETA,
            Vehiculo.VEHICULO,
            Viaje.VIAJE);
    }
}
