/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import model.tables.Convenio;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "CONVENIO", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_C", columnNames = {"ID"})
})
public class ConvenioRecord extends UpdatableRecordImpl<ConvenioRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -302699478;

    /**
     * Setter for <code>TRANSMI.CONVENIO.ID</code>.
     */
    public ConvenioRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.CONVENIO.ID</code>.
     */
    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRANSMI.CONVENIO.EMPRESA</code>.
     */
    public ConvenioRecord setEmpresa(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.CONVENIO.EMPRESA</code>.
     */
    @Column(name = "EMPRESA", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getEmpresa() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TRANSMI.CONVENIO.NUMERO_CONVENIO</code>.
     */
    public ConvenioRecord setNumeroConvenio(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.CONVENIO.NUMERO_CONVENIO</code>.
     */
    @Column(name = "NUMERO_CONVENIO", nullable = false, precision = 10)
    @NotNull
    public Integer getNumeroConvenio() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Convenio.CONVENIO.ID;
    }

    @Override
    public Field<String> field2() {
        return Convenio.CONVENIO.EMPRESA;
    }

    @Override
    public Field<Integer> field3() {
        return Convenio.CONVENIO.NUMERO_CONVENIO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmpresa();
    }

    @Override
    public Integer component3() {
        return getNumeroConvenio();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmpresa();
    }

    @Override
    public Integer value3() {
        return getNumeroConvenio();
    }

    @Override
    public ConvenioRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ConvenioRecord value2(String value) {
        setEmpresa(value);
        return this;
    }

    @Override
    public ConvenioRecord value3(Integer value) {
        setNumeroConvenio(value);
        return this;
    }

    @Override
    public ConvenioRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConvenioRecord
     */
    public ConvenioRecord() {
        super(Convenio.CONVENIO);
    }

    /**
     * Create a detached, initialised ConvenioRecord
     */
    public ConvenioRecord(Integer id, String empresa, Integer numeroConvenio) {
        super(Convenio.CONVENIO);

        set(0, id);
        set(1, empresa);
        set(2, numeroConvenio);
    }
}
