/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import model.tables.Estacion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "ESTACION", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_B", columnNames = {"ID"})
})
public class EstacionRecord extends UpdatableRecordImpl<EstacionRecord> implements Record8<Integer, String, String, String, String, Integer, Long, Integer> {

    private static final long serialVersionUID = 1737023999;

    /**
     * Setter for <code>TRANSMI.ESTACION.ID</code>.
     */
    public EstacionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.ID</code>.
     */
    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.NOMBRE</code>.
     */
    public EstacionRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.NOMBRE</code>.
     */
    @Column(name = "NOMBRE", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.TIENE_TAQUILLA</code>.
     */
    public EstacionRecord setTieneTaquilla(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.TIENE_TAQUILLA</code>.
     */
    @Column(name = "TIENE_TAQUILLA", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    public String getTieneTaquilla() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.UBICACION</code>.
     */
    public EstacionRecord setUbicacion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.UBICACION</code>.
     */
    @Column(name = "UBICACION", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getUbicacion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.SECTOR</code>.
     */
    public EstacionRecord setSector(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.SECTOR</code>.
     */
    @Column(name = "SECTOR", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getSector() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.VIAJE_ID</code>.
     */
    public EstacionRecord setViajeId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.VIAJE_ID</code>.
     */
    @Column(name = "VIAJE_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getViajeId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.VIAJE_DISTANCIA</code>.
     */
    public EstacionRecord setViajeDistancia(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.VIAJE_DISTANCIA</code>.
     */
    @Column(name = "VIAJE_DISTANCIA", nullable = false, precision = 10)
    @NotNull
    public Long getViajeDistancia() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>TRANSMI.ESTACION.RUTA_ID</code>.
     */
    public EstacionRecord setRutaId(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.ESTACION.RUTA_ID</code>.
     */
    @Column(name = "RUTA_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getRutaId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, Integer, Long, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, Integer, Long, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Estacion.ESTACION.ID;
    }

    @Override
    public Field<String> field2() {
        return Estacion.ESTACION.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return Estacion.ESTACION.TIENE_TAQUILLA;
    }

    @Override
    public Field<String> field4() {
        return Estacion.ESTACION.UBICACION;
    }

    @Override
    public Field<String> field5() {
        return Estacion.ESTACION.SECTOR;
    }

    @Override
    public Field<Integer> field6() {
        return Estacion.ESTACION.VIAJE_ID;
    }

    @Override
    public Field<Long> field7() {
        return Estacion.ESTACION.VIAJE_DISTANCIA;
    }

    @Override
    public Field<Integer> field8() {
        return Estacion.ESTACION.RUTA_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getTieneTaquilla();
    }

    @Override
    public String component4() {
        return getUbicacion();
    }

    @Override
    public String component5() {
        return getSector();
    }

    @Override
    public Integer component6() {
        return getViajeId();
    }

    @Override
    public Long component7() {
        return getViajeDistancia();
    }

    @Override
    public Integer component8() {
        return getRutaId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getTieneTaquilla();
    }

    @Override
    public String value4() {
        return getUbicacion();
    }

    @Override
    public String value5() {
        return getSector();
    }

    @Override
    public Integer value6() {
        return getViajeId();
    }

    @Override
    public Long value7() {
        return getViajeDistancia();
    }

    @Override
    public Integer value8() {
        return getRutaId();
    }

    @Override
    public EstacionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EstacionRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public EstacionRecord value3(String value) {
        setTieneTaquilla(value);
        return this;
    }

    @Override
    public EstacionRecord value4(String value) {
        setUbicacion(value);
        return this;
    }

    @Override
    public EstacionRecord value5(String value) {
        setSector(value);
        return this;
    }

    @Override
    public EstacionRecord value6(Integer value) {
        setViajeId(value);
        return this;
    }

    @Override
    public EstacionRecord value7(Long value) {
        setViajeDistancia(value);
        return this;
    }

    @Override
    public EstacionRecord value8(Integer value) {
        setRutaId(value);
        return this;
    }

    @Override
    public EstacionRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Long value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EstacionRecord
     */
    public EstacionRecord() {
        super(Estacion.ESTACION);
    }

    /**
     * Create a detached, initialised EstacionRecord
     */
    public EstacionRecord(Integer id, String nombre, String tieneTaquilla, String ubicacion, String sector, Integer viajeId, Long viajeDistancia, Integer rutaId) {
        super(Estacion.ESTACION);

        set(0, id);
        set(1, nombre);
        set(2, tieneTaquilla);
        set(3, ubicacion);
        set(4, sector);
        set(5, viajeId);
        set(6, viajeDistancia);
        set(7, rutaId);
    }
}
