/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import model.tables.Pasajero;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "PASAJERO", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_7", columnNames = {"ID"})
})
public class PasajeroRecord extends UpdatableRecordImpl<PasajeroRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1626250303;

    /**
     * Setter for <code>TRANSMI.PASAJERO.ID</code>.
     */
    public PasajeroRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.PASAJERO.ID</code>.
     */
    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRANSMI.PASAJERO.NOMBRES</code>.
     */
    public PasajeroRecord setNombres(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.PASAJERO.NOMBRES</code>.
     */
    @Column(name = "NOMBRES", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNombres() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TRANSMI.PASAJERO.EDAD</code>.
     */
    public PasajeroRecord setEdad(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.PASAJERO.EDAD</code>.
     */
    @Column(name = "EDAD", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getEdad() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TRANSMI.PASAJERO.GENERO</code>.
     */
    public PasajeroRecord setGenero(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.PASAJERO.GENERO</code>.
     */
    @Column(name = "GENERO", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    public String getGenero() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Pasajero.PASAJERO.ID;
    }

    @Override
    public Field<String> field2() {
        return Pasajero.PASAJERO.NOMBRES;
    }

    @Override
    public Field<String> field3() {
        return Pasajero.PASAJERO.EDAD;
    }

    @Override
    public Field<String> field4() {
        return Pasajero.PASAJERO.GENERO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombres();
    }

    @Override
    public String component3() {
        return getEdad();
    }

    @Override
    public String component4() {
        return getGenero();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombres();
    }

    @Override
    public String value3() {
        return getEdad();
    }

    @Override
    public String value4() {
        return getGenero();
    }

    @Override
    public PasajeroRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PasajeroRecord value2(String value) {
        setNombres(value);
        return this;
    }

    @Override
    public PasajeroRecord value3(String value) {
        setEdad(value);
        return this;
    }

    @Override
    public PasajeroRecord value4(String value) {
        setGenero(value);
        return this;
    }

    @Override
    public PasajeroRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PasajeroRecord
     */
    public PasajeroRecord() {
        super(Pasajero.PASAJERO);
    }

    /**
     * Create a detached, initialised PasajeroRecord
     */
    public PasajeroRecord(Integer id, String nombres, String edad, String genero) {
        super(Pasajero.PASAJERO);

        set(0, id);
        set(1, nombres);
        set(2, edad);
        set(3, genero);
    }
}
