/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import model.tables.Ruta;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "RUTA", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_2", columnNames = {"ID"})
})
public class RutaRecord extends UpdatableRecordImpl<RutaRecord> implements Record5<Integer, String, String, LocalDate, LocalDate> {

    private static final long serialVersionUID = 1435005675;

    /**
     * Setter for <code>TRANSMI.RUTA.ID</code>.
     */
    public RutaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.RUTA.ID</code>.
     */
    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRANSMI.RUTA.NOMBRE</code>.
     */
    public RutaRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.RUTA.NOMBRE</code>.
     */
    @Column(name = "NOMBRE", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TRANSMI.RUTA.NUMERO</code>.
     */
    public RutaRecord setNumero(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.RUTA.NUMERO</code>.
     */
    @Column(name = "NUMERO", nullable = false, length = 45)
    @NotNull
    @Size(max = 45)
    public String getNumero() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TRANSMI.RUTA.INICIO</code>.
     */
    public RutaRecord setInicio(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.RUTA.INICIO</code>.
     */
    @Column(name = "INICIO", nullable = false, precision = 10)
    @NotNull
    public LocalDate getInicio() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>TRANSMI.RUTA.FIN</code>.
     */
    public RutaRecord setFin(LocalDate value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.RUTA.FIN</code>.
     */
    @Column(name = "FIN", nullable = false, precision = 10)
    @NotNull
    public LocalDate getFin() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDate, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDate, LocalDate> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ruta.RUTA.ID;
    }

    @Override
    public Field<String> field2() {
        return Ruta.RUTA.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return Ruta.RUTA.NUMERO;
    }

    @Override
    public Field<LocalDate> field4() {
        return Ruta.RUTA.INICIO;
    }

    @Override
    public Field<LocalDate> field5() {
        return Ruta.RUTA.FIN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getNumero();
    }

    @Override
    public LocalDate component4() {
        return getInicio();
    }

    @Override
    public LocalDate component5() {
        return getFin();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getNumero();
    }

    @Override
    public LocalDate value4() {
        return getInicio();
    }

    @Override
    public LocalDate value5() {
        return getFin();
    }

    @Override
    public RutaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RutaRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public RutaRecord value3(String value) {
        setNumero(value);
        return this;
    }

    @Override
    public RutaRecord value4(LocalDate value) {
        setInicio(value);
        return this;
    }

    @Override
    public RutaRecord value5(LocalDate value) {
        setFin(value);
        return this;
    }

    @Override
    public RutaRecord values(Integer value1, String value2, String value3, LocalDate value4, LocalDate value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RutaRecord
     */
    public RutaRecord() {
        super(Ruta.RUTA);
    }

    /**
     * Create a detached, initialised RutaRecord
     */
    public RutaRecord(Integer id, String nombre, String numero, LocalDate inicio, LocalDate fin) {
        super(Ruta.RUTA);

        set(0, id);
        set(1, nombre);
        set(2, numero);
        set(3, inicio);
        set(4, fin);
    }
}
