/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import model.tables.Tarjeta;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "TARJETA", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_CF", columnNames = {"ID"})
})
public class TarjetaRecord extends UpdatableRecordImpl<TarjetaRecord> implements Record5<Integer, String, Long, Integer, Integer> {

    private static final long serialVersionUID = -1692938546;

    /**
     * Setter for <code>TRANSMI.TARJETA.ID</code>.
     */
    public TarjetaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.TARJETA.ID</code>.
     */
    @Id
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRANSMI.TARJETA.PERSONALIZADO</code>.
     */
    public TarjetaRecord setPersonalizado(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.TARJETA.PERSONALIZADO</code>.
     */
    @Column(name = "PERSONALIZADO", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    public String getPersonalizado() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TRANSMI.TARJETA.SALDO</code>.
     */
    public TarjetaRecord setSaldo(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.TARJETA.SALDO</code>.
     */
    @Column(name = "SALDO", nullable = false, precision = 10)
    @NotNull
    public Long getSaldo() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>TRANSMI.TARJETA.PASAJERO_ID</code>.
     */
    public TarjetaRecord setPasajeroId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.TARJETA.PASAJERO_ID</code>.
     */
    @Column(name = "PASAJERO_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getPasajeroId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TRANSMI.TARJETA.CONVENIO_ID</code>.
     */
    public TarjetaRecord setConvenioId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.TARJETA.CONVENIO_ID</code>.
     */
    @Column(name = "CONVENIO_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getConvenioId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Long, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Long, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tarjeta.TARJETA.ID;
    }

    @Override
    public Field<String> field2() {
        return Tarjeta.TARJETA.PERSONALIZADO;
    }

    @Override
    public Field<Long> field3() {
        return Tarjeta.TARJETA.SALDO;
    }

    @Override
    public Field<Integer> field4() {
        return Tarjeta.TARJETA.PASAJERO_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Tarjeta.TARJETA.CONVENIO_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPersonalizado();
    }

    @Override
    public Long component3() {
        return getSaldo();
    }

    @Override
    public Integer component4() {
        return getPasajeroId();
    }

    @Override
    public Integer component5() {
        return getConvenioId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPersonalizado();
    }

    @Override
    public Long value3() {
        return getSaldo();
    }

    @Override
    public Integer value4() {
        return getPasajeroId();
    }

    @Override
    public Integer value5() {
        return getConvenioId();
    }

    @Override
    public TarjetaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TarjetaRecord value2(String value) {
        setPersonalizado(value);
        return this;
    }

    @Override
    public TarjetaRecord value3(Long value) {
        setSaldo(value);
        return this;
    }

    @Override
    public TarjetaRecord value4(Integer value) {
        setPasajeroId(value);
        return this;
    }

    @Override
    public TarjetaRecord value5(Integer value) {
        setConvenioId(value);
        return this;
    }

    @Override
    public TarjetaRecord values(Integer value1, String value2, Long value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TarjetaRecord
     */
    public TarjetaRecord() {
        super(Tarjeta.TARJETA);
    }

    /**
     * Create a detached, initialised TarjetaRecord
     */
    public TarjetaRecord(Integer id, String personalizado, Long saldo, Integer pasajeroId, Integer convenioId) {
        super(Tarjeta.TARJETA);

        set(0, id);
        set(1, personalizado);
        set(2, saldo);
        set(3, pasajeroId);
        set(4, convenioId);
    }
}
