/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import model.tables.Viaje;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "VIAJE", schema = "TRANSMI", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_4", columnNames = {"ID", "DISTANCIA"})
})
public class ViajeRecord extends UpdatableRecordImpl<ViajeRecord> implements Record4<Integer, Long, Integer, Integer> {

    private static final long serialVersionUID = -1336789282;

    /**
     * Setter for <code>TRANSMI.VIAJE.ID</code>.
     */
    public ViajeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.VIAJE.ID</code>.
     */
    @Column(name = "ID", nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRANSMI.VIAJE.DISTANCIA</code>.
     */
    public ViajeRecord setDistancia(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.VIAJE.DISTANCIA</code>.
     */
    @Column(name = "DISTANCIA", nullable = false, precision = 10)
    @NotNull
    public Long getDistancia() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>TRANSMI.VIAJE.TARJETA_ID</code>.
     */
    public ViajeRecord setTarjetaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.VIAJE.TARJETA_ID</code>.
     */
    @Column(name = "TARJETA_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getTarjetaId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>TRANSMI.VIAJE.VEHICULO_ID</code>.
     */
    public ViajeRecord setVehiculoId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TRANSMI.VIAJE.VEHICULO_ID</code>.
     */
    @Column(name = "VEHICULO_ID", nullable = false, precision = 10)
    @NotNull
    public Integer getVehiculoId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Long, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Long, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Viaje.VIAJE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Viaje.VIAJE.DISTANCIA;
    }

    @Override
    public Field<Integer> field3() {
        return Viaje.VIAJE.TARJETA_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Viaje.VIAJE.VEHICULO_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDistancia();
    }

    @Override
    public Integer component3() {
        return getTarjetaId();
    }

    @Override
    public Integer component4() {
        return getVehiculoId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDistancia();
    }

    @Override
    public Integer value3() {
        return getTarjetaId();
    }

    @Override
    public Integer value4() {
        return getVehiculoId();
    }

    @Override
    public ViajeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ViajeRecord value2(Long value) {
        setDistancia(value);
        return this;
    }

    @Override
    public ViajeRecord value3(Integer value) {
        setTarjetaId(value);
        return this;
    }

    @Override
    public ViajeRecord value4(Integer value) {
        setVehiculoId(value);
        return this;
    }

    @Override
    public ViajeRecord values(Integer value1, Long value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViajeRecord
     */
    public ViajeRecord() {
        super(Viaje.VIAJE);
    }

    /**
     * Create a detached, initialised ViajeRecord
     */
    public ViajeRecord(Integer id, Long distancia, Integer tarjetaId, Integer vehiculoId) {
        super(Viaje.VIAJE);

        set(0, id);
        set(1, distancia);
        set(2, tarjetaId);
        set(3, vehiculoId);
    }
}
